name: geofileopsdev
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - astroid=2.4.2=py38h32f6830_1
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - babel=2.8.0=py_0
  - boost-cpp=1.74.0=hd4e6614_0
  - brotlipy=0.7.0=py38hab1e662_1001
  - bzip2=1.0.8=he774522_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=hc79e3cf_1005
  - certifi=2020.6.20=py38h9bdc248_2
  - cffi=1.14.3=py38h0e640b1_1
  - cfitsio=3.470=hbbe6aef_7
  - chardet=3.0.4=py38h9bdc248_1008
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - colorama=0.4.3=py_0
  - cryptography=3.2.1=py38hd8c33c5_0
  - curl=7.71.1=h4b64cdc_8
  - docutils=0.16=py38h9bdc248_2
  - expat=2.2.9=h33f27b4_2
  - fiona=1.8.17=py38hcb65fe8_0
  - freetype=2.10.3=hd328e21_0
  - freexl=1.0.5=hd288d7e_1002
  - gdal=3.1.3=py38h8f7194f_1
  - geopandas=0.8.1=py_0
  - geos=3.8.1=he025d50_0
  - geotiff=1.6.0=h8884d1a_3
  - gettext=0.19.8.1=hb01d8f6_1002
  - glib=2.66.1=hccabbfd_0
  - hdf4=4.2.13=hf8e6fe8_1003
  - hdf5=1.10.6=nompi_he0bbb20_101
  - icu=67.1=h33f27b4_0
  - idna=2.10=pyh9f0ad1d_0
  - imagesize=1.2.0=py_0
  - iniconfig=1.0.1=pyh9f0ad1d_0
  - intel-openmp=2020.1=216
  - isort=5.6.4=py_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=he774522_0
  - kealib=1.4.13=h3b59ab9_1
  - krb5=1.17.1=hc04afaa_3
  - lazy-object-proxy=1.4.3=py38h1e8a9f7_2
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libcurl=7.71.1=h4b64cdc_8
  - libffi=3.2.1=ha925a31_1007
  - libgdal=3.1.3=h0e5aa5a_1
  - libiconv=1.16=he774522_0
  - libkml=1.3.0=he9e54da_1012
  - liblapack=3.8.0=16_mkl
  - libnetcdf=4.7.4=nompi_h256d12c_105
  - libpng=1.6.37=ha81a0f5_2
  - libpq=12.3=hd9aa61d_1
  - libspatialindex=1.9.3=he025d50_3
  - libspatialite=5.0.0=hf693123_0
  - libssh2=1.9.0=hb06d900_5
  - libtiff=4.1.0=h885aae3_6
  - libwebp-base=1.1.0=hfa6e2cd_3
  - libxml2=2.9.10=h1006b36_2
  - lz4-c=1.9.2=h62dcd97_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38hab1e662_2
  - mccabe=0.6.1=py_1
  - mkl=2020.1=216
  - more-itertools=8.5.0=py_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - numpy=1.19.2=py38hdf1ac2f_1
  - openjpeg=2.3.1=h57dd2e7_3
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.3=py38h251f6bf_2
  - pcre=8.44=ha925a31_0
  - pip=20.2.4=py_0
  - pixman=0.38.0=hfa6e2cd_1003
  - pluggy=0.13.1=py38h32f6830_3
  - poppler=0.89.0=h5d62644_1
  - poppler-data=0.4.9=1
  - postgresql=12.3=he14cc48_1
  - proj=7.1.1=h7d85306_3
  - psutil=5.7.2=py38hab1e662_1
  - py=1.9.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydata-sphinx-theme=0.4.1=py_0
  - pygments=2.7.2=py_0
  - pylint=2.6.0=py38h32f6830_1
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py38hbdc76b6_3
  - pysocks=1.7.1=py38h9bdc248_2
  - pytest=6.1.1=py38h32f6830_1
  - python=3.8.6=h60c2a47_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - requests=2.24.0=pyh9f0ad1d_0
  - rtree=0.9.4=py38h7ad75cc_1
  - setuptools=49.6.0=py38h9bdc248_2
  - shapely=1.7.1=py38hc96c142_1
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=3.3.0=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.33.0=he774522_1
  - tbb=2020.1=he980bc4_0
  - tiledb=2.1.0=hfabd47f_0
  - tk=8.6.10=he774522_1
  - toml=0.10.1=pyh9f0ad1d_0
  - urllib3=1.25.11=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wheel=0.35.1=pyh9f0ad1d_0
  - win_inet_pton=1.1.0=py38h32f6830_1
  - wincertstore=0.2=py38h32f6830_1005
  - wrapt=1.11.2=py38h1e8a9f7_1
  - xerces-c=3.2.3=ha925a31_1
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.5=h1f3a1b7_2
  - pip:
    - sphinx-automodapi==0.13
